In [1]:
import os
from cot import Collection
from cot.generate import FRAGMENTS
from rich.pretty import pprint
import json

## 1

In [3]:
med_qa = Collection(["med_qa"], verbose=False)

Loading med_qa...

In [8]:
med_qa['med_qa']['test'][1146]

{'id': 'med_qa_test_1146',
 'ref_id': '',
 'question': 'A 27-year-old male presents for emergency surgery to reattach his left arm, severed during a high-speed car accident, and has lost significant amounts of blood. His wife arrives within minutes to the hospital exclaiming that under no circumstance should he receive any blood transfusions during surgery. After reviewing his medical chart, you see also see an annotation indicating no blood transfusions for religious reasons. Knowing that he needs a blood transfusion to save his life, what do you do?',
 'type': 'multiplechoice',
 'choices': ["Administer a blood transfusion to save the patient's life",
  'Call the ethics board of the hospital to discuss the issue',
  "Respect the patient's written instructions and do not adminster a blood transfusion",
  'Convince the wife to administer a blood transfusion to her husband',
  'Refuse to treat the patient as he will die without a blood transfusion'],
 'context': '',
 'cot': [],
 'answer': ["Respect the patient's written instructions and do not adminster a blood transfusion"],
 'generated_cot': [],
 'feedback': []}

In [4]:
medmc_qa = Collection(["medmc_qa"], verbose=False)

Loading medmc_qa...

KeyboardInterrupt:

In [ ]:
pubmed_qa = Collection(["pubmed_qa"], verbose=False)

In [ ]:
'med_qa', 'medmc_qa', 'pubmed_qa'

## 2

In [4]:
coll = Collection.load_thoughtsource_100(names='strategy_qa',load_pregenerated_cots=True)
coll.dump("strategy")
coll = Collection.load_thoughtsource_100(names='commonsense_qa',load_pregenerated_cots=True)
coll.dump("cs")
coll = Collection.load_thoughtsource_100(names='open_book_qa',load_pregenerated_cots=True)
coll.dump("open book")
coll = Collection.load_thoughtsource_100(names='worldtree',load_pregenerated_cots=True)
coll.dump("worldtree")
coll = Collection.load_thoughtsource_100(names='med_qa',load_pregenerated_cots=True)
coll.dump("med")
coll = Collection.load_thoughtsource_100(names='medmc_qa',load_pregenerated_cots=True)
coll.dump("medmc")

Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

## 3

In [53]:
import pandas as pd
df = pd.read_csv("Average_values_df.csv",index_col=False)

df.rename(columns={df.columns[0]: 'dataset'},inplace=True)
#models als rows
#after 10th col, row for every 10 cols

In [59]:
df

,dataset,None_None_command-xlarge-nightly,None_kojima-01_command-xlarge-nightly,None_zhou-01_command-xlarge-nightly,qa-10_None_command-xlarge-nightly,qa-12_None_command-xlarge-nightly,qa-13_None_command-xlarge-nightly,qa-16_None_command-xlarge-nightly,qa-17_None_command-xlarge-nightly,refl-01_None_command-xlarge-nightly,...,None_None_text-davinci-003,None_kojima-01_text-davinci-003,None_zhou-01_text-davinci-003,qa-10_None_text-davinci-003,qa-12_None_text-davinci-003,qa-13_None_text-davinci-003,qa-16_None_text-davinci-003,qa-17_None_text-davinci-003,refl-01_None_text-davinci-003,zhou-01-ins_None_text-davinci-003
0,commonsense_qa,0.52,0.48,0.73,0.70,0.70,0.76,0.67,0.61,0.70,...,0.73,0.67,0.67,0.70,0.79,0.67,0.58,0.64,0.76,0.73
1,med_qa,0.18,0.30,0.27,0.27,0.27,0.24,0.33,0.30,0.21,...,0.30,0.33,0.39,0.36,0.30,0.39,0.36,0.24,0.33,0.36
2,medmc_qa,0.27,0.15,0.42,0.27,0.30,0.36,0.36,0.36,0.24,...,0.36,0.36,0.48,0.45,0.36,0.36,0.39,0.42,0.39,0.33
3,open_book_qa,0.58,0.42,0.61,0.58,0.58,0.58,0.55,0.61,0.61,...,0.64,0.58,0.79,0.73,0.79,0.61,0.64,0.73,0.64,0.82
4,strategy_qa,0.55,0.58,0.24,0.12,0.09,0.12,0.33,0.30,0.06,...,0.61,0.64,0.64,0.58,0.67,0.70,0.55,0.58,0.64,0.64
5,worldtree,0.61,0.61,0.76,0.73,0.82,0.85,0.85,0.64,0.79,...,0.94,0.91,0.82,0.82,0.91,0.85,0.82,0.91,0.91,0.88
6,Average,0.45,0.42,0.51,0.44,0.46,0.48,0.52,0.47,0.43,...,0.60,0.58,0.63,0.61,0.64,0.60,0.56,0.59,0.61,0.63

In [50]:
df.iloc[:, :10]
#split out datasets, take average over models
#split out datasets, take average over prompts

,dataset,None_None_command-xlarge-nightly,None_kojima-01_command-xlarge-nightly,None_zhou-01_command-xlarge-nightly,qa-10_None_command-xlarge-nightly,qa-12_None_command-xlarge-nightly,qa-13_None_command-xlarge-nightly,qa-16_None_command-xlarge-nightly,qa-17_None_command-xlarge-nightly,refl-01_None_command-xlarge-nightly,zhou-01-ins_None_command-xlarge-nightly
0,commonsense_qa,0.52,0.48,0.73,0.70,0.70,0.76,0.67,0.61,0.70,0.73
1,med_qa,0.18,0.30,0.27,0.27,0.27,0.24,0.33,0.30,0.21,0.24
2,medmc_qa,0.27,0.15,0.42,0.27,0.30,0.36,0.36,0.36,0.24,0.33
3,open_book_qa,0.58,0.42,0.61,0.58,0.58,0.58,0.55,0.61,0.61,0.64
4,strategy_qa,0.55,0.58,0.24,0.12,0.09,0.12,0.33,0.30,0.06,0.09
5,worldtree,0.61,0.61,0.76,0.73,0.82,0.85,0.85,0.64,0.79,0.82
6,Average,0.45,0.42,0.51,0.44,0.46,0.48,0.52,0.47,0.43,0.47

In [52]:
df = df.drop(['dataset'], axis=1)
df = df.iloc[:, :10]
average_first_row = df.iloc[0].mean()
average_first_row

0.6599999999999999

In [25]:
example =  pd.read_csv("Average_values_df.csv",index_col=False)
example.columns

Index(['Unnamed: 0', 'None_None_command-xlarge-nightly',
       'None_kojima-01_command-xlarge-nightly',
       'None_zhou-01_command-xlarge-nightly',
       'qa-10_None_command-xlarge-nightly',
       'qa-12_None_command-xlarge-nightly',
       'qa-13_None_command-xlarge-nightly',
       'qa-16_None_command-xlarge-nightly',
       'qa-17_None_command-xlarge-nightly',
       'refl-01_None_command-xlarge-nightly',
       'zhou-01-ins_None_command-xlarge-nightly', 'None_None_flan-T5-xxl',
       'None_kojima-01_flan-T5-xxl', 'None_zhou-01_flan-T5-xxl',
       'qa-10_None_flan-T5-xxl', 'qa-12_None_flan-T5-xxl',
       'qa-13_None_flan-T5-xxl', 'qa-16_None_flan-T5-xxl',
       'qa-17_None_flan-T5-xxl', 'refl-01_None_flan-T5-xxl',
       'zhou-01-ins_None_flan-T5-xxl', 'None_None_gpt-3.5-turbo',
       'None_kojima-01_gpt-3.5-turbo', 'None_zhou-01_gpt-3.5-turbo',
       'qa-10_None_gpt-3.5-turbo', 'qa-12_None_gpt-3.5-turbo',
       'qa-13_None_gpt-3.5-turbo', 'qa-16_None_gpt-3.5-turbo',
       'qa-17_None_gpt-3.5-turbo', 'refl-01_None_gpt-3.5-turbo',
       'zhou-01-ins_None_gpt-3.5-turbo', 'None_None_gpt-4',
       'None_kojima-01_gpt-4', 'None_zhou-01_gpt-4', 'qa-10_None_gpt-4',
       'qa-12_None_gpt-4', 'qa-13_None_gpt-4', 'qa-16_None_gpt-4',
       'qa-17_None_gpt-4', 'refl-01_None_gpt-4', 'zhou-01-ins_None_gpt-4',
       'None_None_text-davinci-002', 'None_kojima-01_text-davinci-002',
       'None_zhou-01_text-davinci-002', 'qa-10_None_text-davinci-002',
       'qa-12_None_text-davinci-002', 'qa-13_None_text-davinci-002',
       'qa-16_None_text-davinci-002', 'qa-17_None_text-davinci-002',
       'refl-01_None_text-davinci-002', 'zhou-01-ins_None_text-davinci-002',
       'None_None_text-davinci-003', 'None_kojima-01_text-davinci-003',
       'None_zhou-01_text-davinci-003', 'qa-10_None_text-davinci-003',
       'qa-12_None_text-davinci-003', 'qa-13_None_text-davinci-003',
       'qa-16_None_text-davinci-003', 'qa-17_None_text-davinci-003',
       'refl-01_None_text-davinci-003', 'zhou-01-ins_None_text-davinci-003'],
      dtype='object')

,None_None_command-xlarge-nightly,None_kojima-01_command-xlarge-nightly,None_zhou-01_command-xlarge-nightly,qa-10_None_command-xlarge-nightly,qa-12_None_command-xlarge-nightly,qa-13_None_command-xlarge-nightly,qa-16_None_command-xlarge-nightly,qa-17_None_command-xlarge-nightly,refl-01_None_command-xlarge-nightly,zhou-01-ins_None_command-xlarge-nightly,...,None_None_text-davinci-003,None_kojima-01_text-davinci-003,None_zhou-01_text-davinci-003,qa-10_None_text-davinci-003,qa-12_None_text-davinci-003,qa-13_None_text-davinci-003,qa-16_None_text-davinci-003,qa-17_None_text-davinci-003,refl-01_None_text-davinci-003,zhou-01-ins_None_text-davinci-003
6,0.45,0.42,0.51,0.44,0.46,0.48,0.52,0.47,0.43,0.47,...,0.6,0.58,0.63,0.61,0.64,0.6,0.56,0.59,0.61,0.63

In [37]:
import numpy as np
df = (df[df.dataset=="Average"])
df = df.drop(['dataset'], axis=1)

AttributeError: 'DataFrame' object has no attribute 'dataset'

In [38]:
new_df = pd.DataFrame(np.reshape(df.values,(6,10)))

In [39]:
rows = ['cohere','flan-t5-xxl','gpt-3.5-turbo','gpt-4','text-davinci-002','text-da-vinci-003']
cols = ['None','kojima-01','zhou-01','qa-10','qa-12','qa-13','qa-16','qa-17','refl-01','zhou-01-ins']
# Change the column names
new_df.columns = cols
  
# Change the row indexes
new_df.index = rows

In [40]:
new_df
#zhou better than instruction

,None,kojima-01,zhou-01,qa-10,qa-12,qa-13,qa-16,qa-17,refl-01,zhou-01-ins
cohere,0.45,0.42,0.51,0.44,0.46,0.48,0.52,0.47,0.43,0.47
flan-t5-xxl,0.62,0.62,0.58,0.60,0.63,0.61,0.54,0.61,0.57,0.59
gpt-3.5-turbo,0.71,0.69,0.70,0.67,0.67,0.66,0.65,0.68,0.65,0.67
gpt-4,0.79,0.83,0.86,0.83,0.80,0.82,0.80,0.78,0.80,0.81
text-davinci-002,0.55,0.49,0.61,0.53,0.58,0.57,0.61,0.49,0.54,0.53
text-da-vinci-003,0.60,0.58,0.63,0.61,0.64,0.60,0.56,0.59,0.61,0.63

In [ ]:
df

In [ ]:
# make new branch

In [16]:
df = (df[df.dataset=="Average"])

In [17]:
df

,dataset,None_None_command-xlarge-nightly,None_kojima-01_command-xlarge-nightly,None_zhou-01_command-xlarge-nightly,qa-10_None_command-xlarge-nightly,qa-12_None_command-xlarge-nightly,qa-13_None_command-xlarge-nightly,qa-16_None_command-xlarge-nightly,qa-17_None_command-xlarge-nightly,refl-01_None_command-xlarge-nightly,...,None_None_text-davinci-003,None_kojima-01_text-davinci-003,None_zhou-01_text-davinci-003,qa-10_None_text-davinci-003,qa-12_None_text-davinci-003,qa-13_None_text-davinci-003,qa-16_None_text-davinci-003,qa-17_None_text-davinci-003,refl-01_None_text-davinci-003,zhou-01-ins_None_text-davinci-003
6,Average,0.45,0.42,0.51,0.44,0.46,0.48,0.52,0.47,0.43,...,0.6,0.58,0.63,0.61,0.64,0.6,0.56,0.59,0.61,0.63

In [60]:
import pandas as pd
df = pd.read_csv("Average_values_df.csv",index_col=False)

df.rename(columns={df.columns[0]: 'dataset'},inplace=True)
#models als rows
#after 10th col, row for every 10 cols
df = df.drop(['dataset'], axis=1)

In [61]:
def average_grouped_cols(df, group_size=10):
    num_groups = df.shape[1] // group_size + (df.shape[1] % group_size > 0)
    
    result_df = pd.DataFrame()
    
    for i in range(num_groups):
        start_col = i * group_size
        end_col = (i + 1) * group_size
        group = df.iloc[:, start_col:end_col]
        group_avg = group.mean(axis=1)
        result_df[f'Group{i+1}Avg'] = group_avg
    
    return result_df

In [62]:
df = average_grouped_cols(df, group_size=10)

In [63]:
df

   Group1Avg  Group2Avg  Group3Avg  Group4Avg  Group5Avg  Group6Avg
0      0.660      0.835      0.688      0.751      0.694      0.694
1      0.261      0.210      0.503      0.646      0.270      0.336
2      0.306      0.339      0.597      0.784      0.394      0.390
3      0.576      0.769      0.760      0.913      0.562      0.697
4      0.248      0.620      0.601      0.817      0.502      0.625
5      0.748      0.814      0.910      0.976      0.877      0.877
6      0.465      0.597      0.675      0.812      0.550      0.605

In [66]:
cols = ['cohere','flan-t5-xxl','gpt-3.5-turbo','gpt-4','text-davinci-002','text-da-vinci-003']
rows = ['commonsense_qa','med_qa','medmc_qa','open_book_qa','strategy_qa','worldtree','average']

In [67]:
df.columns = cols
  
# Change the row indexes
df.index = rows
df

,cohere,flan-t5-xxl,gpt-3.5-turbo,gpt-4,text-davinci-002,text-da-vinci-003
commonsense_qa,0.660,0.835,0.688,0.751,0.694,0.694
med_qa,0.261,0.210,0.503,0.646,0.270,0.336
medmc_qa,0.306,0.339,0.597,0.784,0.394,0.390
open_book_qa,0.576,0.769,0.760,0.913,0.562,0.697
strategy_qa,0.248,0.620,0.601,0.817,0.502,0.625
worldtree,0.748,0.814,0.910,0.976,0.877,0.877
average,0.465,0.597,0.675,0.812,0.550,0.605

In [68]:
df.T

,commonsense_qa,med_qa,medmc_qa,open_book_qa,strategy_qa,worldtree,average
cohere,0.660,0.261,0.306,0.576,0.248,0.748,0.465
flan-t5-xxl,0.835,0.210,0.339,0.769,0.620,0.814,0.597
gpt-3.5-turbo,0.688,0.503,0.597,0.760,0.601,0.910,0.675
gpt-4,0.751,0.646,0.784,0.913,0.817,0.976,0.812
text-davinci-002,0.694,0.270,0.394,0.562,0.502,0.877,0.550
text-da-vinci-003,0.694,0.336,0.390,0.697,0.625,0.877,0.605

In [73]:
#select by prompt
import pandas as pd

def average_col_groups(df):
    max_col_index = df.shape[1]
    result_df = pd.DataFrame()

    for start_col in range(0, 10):
        columns = list(range(start_col, max_col_index, 10))
        group = df.iloc[:, columns]
        group_avg = group.mean(axis=1)
        result_df[f'Group{start_col+1}Avg'] = group_avg

    return result_df

In [74]:
import pandas as pd
df = pd.read_csv("Average_values_df.csv",index_col=False)

df.rename(columns={df.columns[0]: 'dataset'},inplace=True)
#models als rows
#after 10th col, row for every 10 cols
df = df.drop(['dataset'], axis=1)

In [75]:
df = average_col_groups(df)

In [76]:
df

,Group1Avg,Group2Avg,Group3Avg,Group4Avg,Group5Avg,Group6Avg,Group7Avg,Group8Avg,Group9Avg,Group10Avg
0,0.725000,0.698333,0.720000,0.755000,0.725000,0.745000,0.665000,0.650000,0.760000,0.760000
1,0.368333,0.373333,0.393333,0.356667,0.383333,0.366667,0.396667,0.363333,0.351667,0.356667
2,0.453333,0.423333,0.528333,0.473333,0.493333,0.468333,0.510000,0.483333,0.418333,0.431667
3,0.730000,0.683333,0.780000,0.725000,0.740000,0.658333,0.665000,0.698333,0.725000,0.723333
4,0.583333,0.633333,0.596667,0.521667,0.521667,0.608333,0.608333,0.591667,0.491667,0.531667
5,0.870000,0.830000,0.870000,0.855000,0.915000,0.890000,0.835000,0.840000,0.865000,0.900000
6,0.620000,0.605000,0.648333,0.613333,0.630000,0.623333,0.613333,0.603333,0.600000,0.616667

In [78]:
cols = ['None','kojima-01','zhou-01','qa-10','qa-12','qa-13','qa-16','qa-17','refl-01','zhou-01-ins']
rows = ['commonsense_qa','med_qa','medmc_qa','open_book_qa','strategy_qa','worldtree','average']
df.columns = cols
  
# Change the row indexes
df.index = rows
rounded_df = df.round(decimals=2)
rounded_df

,None,kojima-01,zhou-01,qa-10,qa-12,qa-13,qa-16,qa-17,refl-01,zhou-01-ins
commonsense_qa,0.72,0.70,0.72,0.76,0.72,0.74,0.66,0.65,0.76,0.76
med_qa,0.37,0.37,0.39,0.36,0.38,0.37,0.40,0.36,0.35,0.36
medmc_qa,0.45,0.42,0.53,0.47,0.49,0.47,0.51,0.48,0.42,0.43
open_book_qa,0.73,0.68,0.78,0.72,0.74,0.66,0.66,0.70,0.72,0.72
strategy_qa,0.58,0.63,0.60,0.52,0.52,0.61,0.61,0.59,0.49,0.53
worldtree,0.87,0.83,0.87,0.86,0.92,0.89,0.84,0.84,0.87,0.90
average,0.62,0.60,0.65,0.61,0.63,0.62,0.61,0.60,0.60,0.62

## 4

In [2]:
from cot import Collection
col = Collection.from_json("single_meta_experiment_prompt_5_gpt_4.json")

/opt/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/robertpraas/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [3]:
col.evaluate()

  0%|          | 0/28 [00:00<?, ?ex/s]

  0%|          | 0/24 [00:00<?, ?ex/s]

{'commonsense_qa': {'validation': {'accuracy': {'gpt-4': {'None_praas-05_kojima-A-E': 0.285714,
     'None_zhou-01_kojima-A-E': 0.0}}}},
 'med_qa': {'test': {'accuracy': {'gpt-4': {'None_zhou-01_kojima-A-E': 0.0}}}}}